name: Android Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        pip install buildozer cython==0.29.34
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Clean previous builds
      run: buildozer appclean

    - name: Accept SDK licenses
      run: yes | /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-apk
        path: bin/*.apk
